[application]
name = "proyecto"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Cars"

[web.watcher]
reload_html = true
index_on_404 = true
watch_path = ["src", "public", "index.html"]

[web.resource]
style = [
  '/assets/tailwind.css',
]
script = [
#  '/assets/tailwind.config.js',
]

[web.resource.dev]
script = []
